apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: helloworld-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld-container
          image: phill97/helloworld:latest
          env:
          - name: NAME
            value: Philip
          - name: LISTEN
            value: :5000
